---
title: "Week 37 James Patterson Books Checked Out"
author: "Joe Rubash"
date: "September 8, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# 01 - Load  libraries----------------------------------------------------------
library(tidyverse)
library(lubridate)
library(ggthemes)
library(wesanderson)
library(scales)



# 02 - Load and save data-------------------------------------------------------
# data URL
file.url <- "https://query.data.world/s/a4iixd7igtgqkg5pvzcsu5smuuwzob"

# function to read in data from net
load_data_from_net <- function(file.url){
    read.csv(file.url, 
             header = TRUE,
             stringsAsFactors = FALSE)
}

# once read from net save to csv in data folder
csv.file <- "./data/James.Patterson.Books.csv"

data <- if(file.exists(csv.file)) {
         read_csv(csv.file)
    } else{
        load_data_from_net(file.url) %>% 
        write_csv(., "./data/James.Patterson.Books.csv")
    }


# 03 - Format data--------------------------------------------------------------
# fix variable names
names(data) <- tolower(names(data))

# change the name to the first variable to be more readable
names(data)[names(data) == "ï..material.type"] <- "material.type"

# change the following variables to factors
data <- modify_at(.x = data,
                  .at = c("material.type",
                          "title",
                          "series",
                          "checkout.year",
                          "checkout.month",
                          "subjects",
                          "publisher",
                          "publication.year"),
                  as.factor)

# create a variable for year and month combined
data <- data %>% 
    mutate(year.month = paste(checkout.year, checkout.month, "1") %>% 
               ymd(.))

# perhaps create variable for the type of book... thriller, fiction, scifi etc.

```
```{r first look at data}
# try to understand structure of data
glimpse(data)

summary(data)

```
```{r checkouts over time}
# summarize number of checkouts by year, month and title
sum.data <- data %>% 
    group_by(checkout.year,
             checkout.month,
             title,
             year.month) %>% 
    summarise(num.checkouts = sum(checkouts)) %>% 
    ungroup() %>% 
    top_n(20)

ggplot(data = sum.data,
       aes(x = checkout.month,
           y = num.checkouts,
           color = title,
           group = title))+
    geom_line()+
    geom_point()+
    facet_wrap(~checkout.year, 
               scales = "free_x")
```
```{r titles ordered by number of checkout}
# sort title by number of checkouts for each year 
title.data <- data %>% 
    group_by(checkout.year,
             title) %>%
    summarise(num.checkout = sum(checkouts)) %>% 
    arrange(desc(num.checkout),
            .by_group = TRUE) %>% 
    mutate(title.index = row_number()) %>% 
    top_n(5)

# create bar plot
ggplot(data = title.data,
       aes(x = title.index,
           y = num.checkout))+
    geom_bar(stat = "identity")+
    facet_wrap(~ checkout.year, 
               scales = "free_x")+
    scale_x_continuous(breaks = title.data$title.index,
                       labels = title.data$title)

    
```
```{r top 10 James Patterson books}
# 1. determine top ten books by number of checkouts
top.10 <- data %>% 
    group_by(title) %>% 
    summarise(num.checkouts = sum(checkouts)) %>% 
    arrange(desc(num.checkouts)) %>%
    top_n(10)

# 2. find release dates for top ten books
release.top.10 <- data %>% 
    filter(title %in% c(as.character(top.10$title))) %>% 
    group_by(title) %>% 
    summarise(first.checkout = min(year.month)) %>% 
    arrange(first.checkout)

# 3. create data set filtered by top.10
top.10.data <- data %>% 
    group_by(checkout.year, # summarize data by year and month
             checkout.month,
             year.month,
             title) %>% 
    summarise(num.checkouts = sum(checkouts)) %>% 
    filter(title %in% c(as.character(top.10$title))) %>% # keep only top ten titles
    mutate(title = fct_relevel(title,
                               c(as.character(release.top.10$title)))) # order titles


# 4. Determine max number of checkouts for any given month for top 10 titles
top.10.data.max <- top.10.data %>% 
    group_by(title) %>% 
    summarise(max.checkouts = max(num.checkouts))

# 5. merge top checkouts by title with release.top.10
top.10.labels <- merge(release.top.10, top.10.data.max) %>% 
    arrange(first.checkout)



# create plot with top ten books
windows()
ggplot(data = top.10.data,
       aes(x = year.month,
           y = num.checkouts,
           fill = as.integer(fct_relevel(title, 
                            c(as.character(top.10.labels$title)))),
           group = fct_relevel(title, 
                            c(as.character(top.10.labels$title)))))+
    geom_area()+
    facet_grid(fct_relevel(title, 
                            c(as.character(top.10.labels$title))) ~ .)+
    geom_text(data = top.10.labels,
        aes(x = first.checkout,
                  y = max.checkouts + 25,
                  color = as.integer(fct_relevel(title, 
                            c(as.character(title)))),
                  label = fct_relevel(title, 
                            c(as.character(title))),
        hjust = 0))+
    theme_tufte()+
    theme(strip.text.y = element_blank(),
          legend.position = "none",
          title = element_text(size = 16),
          text = element_text(size = 12))+
    coord_cartesian(ylim = c(0, max(top.10.labels$max.checkouts) + 40))+
    scale_x_date(date_breaks = "1 years",
                 date_labels = "%Y")+
    labs(x = "",
         y = "Number of Books Checked Out / Month",
         title = "Top 10 Most Checked Out James Patterson Books from The Seattle Public Library",
         subtitle = "Number of times each title was checked out each month peaked just after release but then slowly died off with time")+
    scale_fill_gradient(low = "#CC0000", high = "#999999")+
    scale_color_gradient(low = "#CC0000", high = "#999999")
    
ggsave("./output/top.10.James.Patterson.books.png",
       width = 10,
       height = 6)
```

